// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdP951dvSx1tl5zMtRsL0xCctmU3KHq5c',
    appId: '1:186120937530:web:a811db437a9b695e289503',
    messagingSenderId: '186120937530',
    projectId: 'family-blog-59f6f',
    authDomain: 'family-blog-59f6f.firebaseapp.com',
    storageBucket: 'family-blog-59f6f.firebasestorage.app',
    measurementId: 'G-F2V46YV0L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEkmmDacqdEK-prIC03qAiogTdy1uX1q4',
    appId: '1:186120937530:android:6237f3740cb26fd3289503',
    messagingSenderId: '186120937530',
    projectId: 'family-blog-59f6f',
    storageBucket: 'family-blog-59f6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgNHHbjmUcUFsPiuWYXuA9RxVgjVMNCio',
    appId: '1:186120937530:ios:017f3f79c3171a39289503',
    messagingSenderId: '186120937530',
    projectId: 'family-blog-59f6f',
    storageBucket: 'family-blog-59f6f.firebasestorage.app',
    iosBundleId: 'com.example.famillyBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgNHHbjmUcUFsPiuWYXuA9RxVgjVMNCio',
    appId: '1:186120937530:ios:017f3f79c3171a39289503',
    messagingSenderId: '186120937530',
    projectId: 'family-blog-59f6f',
    storageBucket: 'family-blog-59f6f.firebasestorage.app',
    iosBundleId: 'com.example.famillyBlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdP951dvSx1tl5zMtRsL0xCctmU3KHq5c',
    appId: '1:186120937530:web:3998a97eae2dd4d6289503',
    messagingSenderId: '186120937530',
    projectId: 'family-blog-59f6f',
    authDomain: 'family-blog-59f6f.firebaseapp.com',
    storageBucket: 'family-blog-59f6f.firebasestorage.app',
    measurementId: 'G-XZEF70ZZLR',
  );
}
